name: Update_m3u8

on:
  push:
    branches:
      - master
    schedule:
      - cron: '2 4 * * *'
jobs:
  csdn-emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Update list
        run: |
          # cd paper_infos
          python update_m3u8.py

      - name: Add & Commit
        uses: EndBug/add-and-commit@v8.0.2

        with:
          # author_name: Your Name
          # author_email: mail@example.com
          message: "update"
          add: "*.m3u8"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
